baseurl: "https://olymvis.netlify.app/"
languageCode: "en-us"
title: "Olymvis"
theme: "hugo-prose"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
paginate: 1

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  header:
    - name: Home
      url: "/"
      weight: 1
    - name: Paper
      url: "/paper/"
      weight: 2
  footer:
    - name: Website Repo
      url: "https://github.com/hongtaoh/olymvis"
      weight: 1
    - name: Data Repo
      url: "https://github.com/hongtaoh/olymvis-data"
      weight: 2
    - name: Back to top
      url: "/#top"

params:
  homePosts: 0
  editLink: "https://github.com/hongtaoh/olymvis/edit/master/content/"
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    A website built through Hugo  with the hugo-prose theme.
  footer: >
    &copy; [Chris Fang]() & [Hongtao Hao](https://hongtaoh.com/)
    2020
  license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
    licensed under MIT. The full source of this website is available at
    https://github.com/hongtaoh/olymvis. The source code of data manipulation
    and visualization is available at https://github.com/hongtaoh/olymvis-data.

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
